# Generated by Django 5.2 on 2026-05-12 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField()),
                ('password', models.CharField()),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(default='user')),
            ],
        ),
    ]
