# Generated by Django 5.2 on 2026-05-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(null=True),
        ),
    ]
